const featured=document.querySelector('#featuredGrid'),archive=document.querySelector('#archiveList');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const FEATURED = [
  {id:'carro', title:'“Gracias a Dios no pasó a mayores”: así resisten los vecinos del barrio sacudido por el carro bomba', dek:'La vida cotidiana después de una noche que alteró la tranquilidad.', type:'CRÓNICA', url:'https://www.elpais.com.co/cali/gracias-a-dios-no-paso-a-mayores-asi-resisten-los-vecinos-del-barrio-sacudido-por-el-carro-bomba-en-cali-2321.html', image:'https://www.elpais.com.co/resizer/v2/MZEEEHSLABHQ5AYQHAZMJVTEQ4.jpeg?auth=acc717fbba1ffe907b447f779d4d7de057b92b9d52c079fd8e2ea15e3fc8cb88&smart=true&quality=75&width=768&fitfill=false'},
  {id:'solar', title:'Los comedores comunitarios del oriente de Cali que ahora cocinan con energía solar', dek:'Alimentación, comunidad y energías limpias.', type:'CIUDAD', url:'https://www.elpais.com.co/cali/los-comedores-comunitarios-del-oriente-de-cali-que-ahora-cocinan-con-energia-solar-2512.html', image:'https://www.elpais.com.co/resizer/v2/6RHOKUN54NDBLORMZLJGAQT6NU.jpeg?auth=c73431249e5b9ee9b8237e80bfcbb685df722edcd4321d39f717f2f6050fb0a8&smart=true&quality=75&width=768&height=432'},
  {id:'kdot', title:'El artista del oriente de Cali al que Kendrick Lamar le compró una obra', dek:'La historia detrás de una obra que llegó hasta una estrella mundial.', type:'CULTURA', url:'https://www.elpais.com.co/cali/el-artista-del-oriente-de-cali-al-que-kendrick-lamar-le-compro-una-obra-esta-es-su-historia-1220.html', image:'https://www.elpais.com.co/resizer/v2/GQNX4PYKTZACLCJ6W63YAPMIZI.jpg?auth=7d6560cfd2e8e898c5842b4ede5144f7032e65b9ae7a1e9531316e9df5eeb710&smart=true&quality=75&width=1280&fitfill=false'},
  {id:'mina', title:'La mina que arde hace 100 años, a pocos minutos de Cali', dek:'Una historia del territorio y la minería.', type:'REPORTAJE', url:'https://www.elpais.com.co/valle/la-mina-que-arde-hace-100-anos-a-pocos-minutos-de-cali-0802.html', image:'https://www.elpais.com.co/resizer/v2/JYOJRJEBKZFSLC4QKVLEFWNCGA.jpg?auth=8356d6f856bd50ee4016ad6bf85ffc2c83fd68b70b544a4341de94a1341f8305&smart=true&quality=75&width=768&height=432'},
  {id:'moscas', title:'Las moscas y su innovador aprovechamiento en el Valle del Cauca', dek:'Una alternativa para reducir costos en el sector agrícola.', type:'REPORTAJE', url:'https://www.elpais.com.co/valle/las-moscas-y-su-innovador-aprovechamiento-en-el-valle-del-cauca-para-reducir-los-costos-en-el-sector-agricola-0850.html', image:'https://www.elpais.com.co/resizer/v2/UWUTSIQMDJA2XAXIQ4SHXMKYHU.jpeg?auth=1d87c9574ff23529f606215da1811b3a7afd2182f8a4f54f0b5b41fa1c93fb7f&smart=true&quality=75&width=768&fitfill=false'},
  {id:'explosiones', title:'Mirando para todos lados: las secuelas que dejaron las explosiones en Cali', dek:'Las huellas que permanecen en quienes vivieron episodios de violencia.', type:'REPORTAJE', url:'https://www.elpais.com.co/judicial/mirando-para-todos-lados-las-secuelas-que-dejaron-las-explosiones-en-cali-1013.html', image:'https://www.elpais.com.co/resizer/v2/PIO7L5QC6FGBTCXIB6EZ3N5FAA.JPG?auth=cbaeaa337a8cec80067238feebefca4d79e2157ac32d72db1ad37193b554ccd7&smart=true&quality=75&width=768&height=432'},
  {id:'alas', title:'Alas por el mundo: la familia argentina que convirtió un bus en su casa', dek:'Una familia viajera llegó a Cali con su casa sobre ruedas.', type:'CRÓNICA', url:'https://www.elpais.com.co/cali/alas-por-el-mundo-la-familia-argentina-que-convirtio-un-bus-en-su-casa-y-ahora-esta-en-cali-2039.html', image:'https://www.elpais.com.co/resizer/v2/IN5VFNSTARAMXFOXQYADG5DZTA.png?auth=57bc5ce51ed4f4f8c8082170b289aeb1b9fe9257ac138b3c86eb2d646b4f361f&smart=true&quality=75&width=768&height=432'},
  {id:'transito', title:'Así se vive una noche de retenes en Cali', dek:'Multas, peleas y vehículos inmovilizados durante una noche de controles.', type:'CIUDAD', url:'https://www.elpais.com.co/cali/asi-se-vive-un-operativo-nocturno-de-transito-en-cali-multas-peleas-y-vehiculos-inmovilizados-1913.html', image:'https://www.elpais.com.co/resizer/v2/AQ6JFDR6AZFLLBSF2QKXE4QJCA.jpg?auth=6fc68c096ae9d7ea306b95379548fdec77fe73f3133cd335e2df489c1da8b1a4&smart=true&quality=75&width=768&height=432'}
];
function renderFeatured(){featured.innerHTML=FEATURED.map((w,i)=>`<article class="card ${i===0?'card-large':''}"><a class="card-image-link" href="${esc(w.url)}" target="_blank" rel="noopener" aria-label="Leer ${esc(w.title)} en El País"><div class="card-image"><img src="${esc(w.image)}" alt="Portada: ${esc(w.title)}" loading="lazy"></div></a><div class="card-body"><div class="card-meta"><span>${esc(w.type)}</span><span>DESTACADO</span></div><h3>${esc(w.title)}</h3><p>${esc(w.dek)}</p><a href="${esc(w.url)}" target="_blank" rel="noopener">LEER EN EL PAÍS ↗</a></div></article>`).join('')}
function renderArchive(filter='TODOS'){archive.innerHTML=WORKS.filter(w=>filter==='TODOS'||w.type===filter).map(w=>`<a class="archive-row" href="${esc(w.url)}" target="_blank" rel="noopener"><span class="date"></span><span class="type">${esc(w.type)}</span><h3>${esc(w.title)}</h3><span class="publication">EL PAÍS</span><span class="plus">+</span></a>`).join('')}
renderFeatured();renderArchive();
document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderArchive(b.dataset.filter)}));
document.querySelector('#navToggle').addEventListener('click',()=>document.querySelector('.nav nav').classList.toggle('open'));
const modal=document.querySelector('#modal'),frame=document.querySelector('#pdfFrame'),pdfNewTab=document.querySelector('#pdfNewTab');document.querySelectorAll('.paper').forEach(p=>p.addEventListener('click',()=>{const pdf=p.dataset.pdf;frame.src=pdf+'#toolbar=1&navpanes=0&view=FitH';pdfNewTab.href=pdf;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));const closePdf=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');frame.src='';pdfNewTab.href='#';document.body.style.overflow=''};document.querySelector('#closeModal').addEventListener('click',closePdf);modal.addEventListener('click',e=>{if(e.target===modal)closePdf()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closePdf()});
window.addEventListener('scroll',()=>{const h=document.documentElement,max=h.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(max>0?scrollY/max*100:0)+'%'});
